# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movie.Genere'),
        ),
    ]
